// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaCore.Data;

namespace PizzaCore.Migrations {
  [DbContext(typeof(PizzaCoreContext))]
  [Migration("20211201190355_OrderModelExtended")]
  partial class OrderModelExtended {
    protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("Relational:MaxIdentifierLength", 128)
          .HasAnnotation("ProductVersion", "5.0.12")
          .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity("PizzaCore.Data.Entities.Product", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int")
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        b.Property<string>("Category")
            .HasColumnType("nvarchar(max)");

        b.Property<string>("Description")
            .HasColumnType("nvarchar(max)");

        b.Property<string>("ImageId")
            .HasColumnType("nvarchar(max)");

        b.Property<string>("Name")
            .HasColumnType("nvarchar(max)");

        b.HasKey("Id");

        b.ToTable("Products");
      });

      modelBuilder.Entity("PizzaCore.Data.Entities.ProductSize", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int")
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        b.Property<double>("Price")
            .HasColumnType("float");

        b.Property<int>("ProductId")
            .HasColumnType("int");

        b.Property<string>("Size")
            .HasColumnType("nvarchar(max)");

        b.HasKey("Id");

        b.HasIndex("ProductId");

        b.ToTable("ProductSizes");
      });

      modelBuilder.Entity("PizzaCore.Models.CareersModel", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int")
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        b.Property<byte[]>("CVBinary")
            .HasColumnType("varbinary(max)");

        b.Property<DateTime>("Date")
            .HasColumnType("datetime2");

        b.Property<string>("Email")
            .IsRequired()
            .HasMaxLength(30)
            .HasColumnType("nvarchar(30)");

        b.Property<string>("FirstName")
            .IsRequired()
            .HasColumnType("nvarchar(max)");

        b.Property<string>("LastName")
            .IsRequired()
            .HasMaxLength(50)
            .HasColumnType("nvarchar(50)");

        b.Property<string>("Position")
            .IsRequired()
            .HasColumnType("nvarchar(max)");

        b.HasKey("Id");

        b.ToTable("CareersModels");
      });

      modelBuilder.Entity("PizzaCore.Models.ContactModel", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int")
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        b.Property<DateTime>("Date")
            .HasColumnType("datetime2");

        b.Property<string>("Email")
            .IsRequired()
            .HasMaxLength(30)
            .HasColumnType("nvarchar(30)");

        b.Property<string>("FirstName")
            .IsRequired()
            .HasMaxLength(50)
            .HasColumnType("nvarchar(50)");

        b.Property<string>("LastName")
            .IsRequired()
            .HasMaxLength(50)
            .HasColumnType("nvarchar(50)");

        b.Property<string>("Message")
            .IsRequired()
            .HasMaxLength(500)
            .HasColumnType("nvarchar(500)");

        b.Property<string>("Topic")
            .IsRequired()
            .HasColumnType("nvarchar(max)");

        b.HasKey("Id");

        b.ToTable("ContactModels");
      });

      modelBuilder.Entity("PizzaCore.Models.OrderModel", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int")
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        b.Property<string>("Address")
            .IsRequired()
            .HasColumnType("nvarchar(max)");

        b.Property<string>("City")
            .IsRequired()
            .HasMaxLength(50)
            .HasColumnType("nvarchar(50)");

        b.Property<DateTime>("Date")
            .HasColumnType("datetime2");

        b.Property<string>("Email")
            .IsRequired()
            .HasMaxLength(30)
            .HasColumnType("nvarchar(30)");

        b.Property<string>("FirstName")
            .IsRequired()
            .HasMaxLength(50)
            .HasColumnType("nvarchar(50)");

        b.Property<string>("LastName")
            .IsRequired()
            .HasMaxLength(50)
            .HasColumnType("nvarchar(50)");

        b.Property<string>("Payment")
            .IsRequired()
            .HasColumnType("nvarchar(max)");

        b.Property<string>("Phone")
            .HasColumnType("nvarchar(max)");

        b.Property<string>("PostalCode")
            .IsRequired()
            .HasColumnType("nvarchar(max)");

        b.HasKey("Id");

        b.ToTable("OrderModels");
      });

      modelBuilder.Entity("PizzaCore.Data.Entities.ProductSize", b => {
        b.HasOne("PizzaCore.Data.Entities.Product", "Product")
            .WithMany("ProductSizes")
            .HasForeignKey("ProductId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("Product");
      });

      modelBuilder.Entity("PizzaCore.Data.Entities.Product", b => {
        b.Navigation("ProductSizes");
      });
#pragma warning restore 612, 618
    }
  }
}
